### ISSUE TITLE
Tooltip: missing trend & CSS

### ISSUE THREAD

**Issue by ecow** [linkeddatacenter/LODMAP2D#20]
Nel tooltip manca l'indicazione del trend e un ragionevole css

**Comment by miahmohd** [comment]
nel tooltip c'è la percentuale, e anche  il css

**Comment by miahmohd** [comment]
se con l'indicazione del trend intendi mettere il colore come sfondo della percentuale, quello non possiamo farlo perchè qua i colori non sono predeterminati e c'è il rischio che dopo non sia più leggibile la percentuale.
possiamo pensare ad un altro modo per aggiungere il colore, ma non come sfondo dell apercentuale come prima.
