### ISSUE TITLE
Changes in data.ttl don't show up on the interface

### ISSUE THREAD

**Issue by gustavopdias** [linkeddatacenter/LODMAP2D#58]
Hello all!

I'm trying to customize the data.ttl so that titles and subtitles in the webpage are translated from italian to portuguese. I made the edits in the data.ttl file using VScode, but when I restart the docker image, nothing changes. What is happening?

**Comment by ecow** [comment]
Did you clean the cache? Did you rebuild the image?

**Comment by gustavopdias** [comment]
I believe so. This is what I'm running in docker:

![Capture20](https://user-images.githubusercontent.com/62766836/116791490-1426d080-aa91-11eb-9f6a-67806fe5184a.JPG)

And this is my directory:

![Capture21](https://user-images.githubusercontent.com/62766836/116791530-74b60d80-aa91-11eb-93c0-9a6801fc0193.JPG)

My localhost:8080 is just a blank page.

**Comment by ecow** [comment]
Hum it is strange...
the build command should be `docker build -t myloadmap2d -f docker/Dockerfile .`

Anyway you should also define  LODMAP2D_DATA pointing to your datafile. ie:

```
docker run -d -e LODMAP2D_DATA=http://localhost:8080/data.ttl  -p 8080:80 myloadmap2d
```

You shoud be able also to save your data in a public endpoint (**warning about CORS**) and just use it from  the  published docker:

```
docker run -d -e LODMAP2D_DATA=http://hereyourwebdataprovider/data.ttl  -p 8080:80 linkeddatacenter/lodmap2d
```

**Comment by gustavopdias** [comment]
Thanks for the reply. Unfortunately, these commands still haven't solved my problem.  

Here are the outputs I got from them:

![image](https://user-images.githubusercontent.com/62766836/116919090-2f2b4900-ac27-11eb-838b-1e7bfc01a4b1.png)


C:\Users\gusta\sploadmap>docker run -d -e LODMAP2D_DATA=http://localhost:8080/data.ttl  -p 8080:80 myloadmap2d
140f0dbfd93a4a68ea23ea2de74cf486b3a1f1c293822bd7bd9a28cb163cb04f`



And here is my docker log:

![image](https://user-images.githubusercontent.com/62766836/116919070-263a7780-ac27-11eb-849b-1a2578e73409.png)


And just to let you know I'm using Chrome.

**Comment by ecow** [comment]
please could you send me your data file? 

This the test I made:
- I copied public/data.ttl into public/mydata.ttl
- I edited  public/mydata.ttl doing some changes to some strings
- I rebuild the docker image  with the command `docker build -t myloadmap2d -f docker/Dockerfile .`
- I run `docker run -d -e LODMAP2D_DATA=http://localhost:8080/mydata.ttl -p 8080:80 myloadmap2d`
- I cleanup the browser cache
- I point my chrome browser to http://localhost:8080/ 

... and I can see the demo with my edited data file. Just running `docker run -d -e LODMAP2D_DATA=http://localhost:8080/data.ttl -p 8080:80 myloadmap2d` I can see the standard demo file.

**Comment by gustavopdias** [comment]
Ok. This is my data.ttl file (I just changed the string "Stato" to "Geral":

`#
# Copyright (c) 2019 LinkedData.Center.
# Commented properties cna be inferred by a BGO reasoner
#
# Please test before publishing with http://rdf-translator.appspot.com/
#
@prefix bgo: <http://linkeddata.center/lodmap-bgo/v1#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix : <urn:bgo:test:> .



############################################
# Application framework
############################################

:domain # a bgo:Domain ;
	bgo:title "Live test of Bubble Graph Ontology" ;
    bgo:description "Here a short description of the data domain" ;
    bgo:abstract "These are **demo data** without a real meaning."^^bgo:MDString ;

    # add an item to default navigation menu
    bgo:hasNavigationMenu [
    	# a bgo:NavigationMenu ;
    	bgo:withCustomMenuItem
    		[
    			# a bgo:MenuItem ;
				bgo:icon "mdi-atom-variant" ;
				bgo:title "reference implementation..." ;
				bgo:link <https://github.com/linkeddatacenter/LODMAP2D>
			]
    ] ;

    # Use the Option menu with two external links
    bgo:hasOptionMenu [
    	# a bgo:OptionMenu ;
    	bgo:withCustomMenuItem
    		[
    			# a bgo:MenuItem ;
				bgo:icon "mdi-information-outline" ;
				bgo:title "about LODMAP2D..." ;
				bgo:link <http://bit.ly/lodmap2d_p>
			] ,
    		[
    			# a bgo:MenuItem ;
				bgo:icon "mdi-lock" ;
				bgo:title "about WebID-OIDC..." ;
				bgo:link <https://github.com/solid/webid-oidc-spec>
			]

    ] ;

    # Add just a couple of shortcuts icons to footer
    bgo:hasFooterMenu [
    	# a bgo:FooterMenu ;
    	bgo:withCustomMenuItem
    		[
    			# a bgo:MenuItem
		    	bgo:title "GitHub" ;
				bgo:link <https://github.com/linkeddatacenter/LODMAP2D>
			]
    ] ;

    # This domain likes social
    bgo:hasSocialSharing 1 ;

    # This should be used if copyright is not present
    bgo:hasCopyrigth "(c) [LinkedData.Center](http://linkeddata.center)"^^bgo:MDString ;

    bgo:hasOverview :overview ;
    bgo:hasTableView :table_view ;
    bgo:hasCredits :credits_page ;
    bgo:hasTerms :terms_page ;
    bgo:hasAccountView  :account_view ;
.


############################################
# Account view
############################################
:account_view
	# a bgo:AccountView ;
    bgo:amountFormatter :amount_formatter;
    bgo:referenceFormatter :amount_formatter;
    bgo:trendFormatter :trend_formatter;

	bgo:hasHistoricalPerspective [
		# a bgo:HistoricalPerspective ;
		bgo:title "Storico dell'azione" ;
	    bgo:amountFormatter :smart_formatter
	];
	bgo:hasBreakdownPerspective [
		# a bgo:BreakdownPerspective ;
		bgo:title "Dettaglio capitoli di spesa" ;
	    bgo:amountFormatter :smart_formatter;
	    bgo:hasTotalizer :filtered_total_formatter ;
	]
.

:amount_formatter
    # a bgo:NumberFormatter ;
	bgo:format "€ %s"^^bgo:Template  ;
	bgo:precision 2 ;
.

:smart_formatter
	# a bgo:NumberFormatter ;
	bgo:format "€ %s"^^bgo:Template  ;
	bgo:precision 0 ;
	bgo:maxValue 999999999.99 ;
	bgo:minValue 0.005 ;
	bgo:nanFormat "non definito" ;
	bgo:moreThanMaxFormat "molto grande"^^bgo:Template ;
	bgo:lessThanMinFormat "molto piccolo"^^bgo:Template
.

:trend_formatter
	# a bgo:NumberFormatter ;
	bgo:format "%s%"^^bgo:Template  ;
	bgo:scaleFactor 100 ;
	bgo:precision 2 ;
	bgo:maxValue 100;
	bgo:minValue -100 ;
	bgo:nanFormat "non disponibile" ;
	bgo:moreThanMaxFormat ">100%"^^bgo:Template ;
	bgo:lessThanMinFormat "<-100%"^^bgo:Template
.

############################################
# Credits
############################################

:credits_page
	# a bgo:CreditsView ;
    bgo:icon "fas fa-users";
	bgo:title "Credits"@en ;
	bgo:abstract
"""
This code was written by:

- [Miah Mohd Ehtesham](https://github.com/miahmohd)
- [Leonardo Longhi](https://github.com/LeonardoLonghi)
- [Yassine Ouahidi](https://github.com/YassineOuahidi)
- [Enrico Fagnoni](https://github.com/ecow)

Using following great open source components:

- The [D3.js library](https://d3js.org/)
- The [Vue javascript framework](https://vuejs.org)
- [rdflib project](https://github.com/linkeddata/rdflib.js) by TimBL & LinkedData team
- the [SOLID](https://github.com/solid/solid-spec) specifications

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

"""^^bgo:MDString.


############################################
# Terms
############################################


:terms_page
	# a bgo:TermsView ;
    bgo:icon  "fas fa-gavel" ;
	bgo:title "Terms & conditions" ;
	bgo:abstract
"""
here palace your **Terms & conditions** about published service.
"""^^bgo:MDString.



#######################################################
# Partitions
#######################################################

:table_view
	# a bgo:TableView ;
	bgo:title "Table view";
    bgo:hasTotalizer :filtered_total_formatter ;
    bgo:amountFormatter :amount_formatter;
    bgo:referenceFormatter :amount_formatter;
    bgo:trendFormatter :trend_formatter;
    bgo:hasSearchPane :search_pane ;
    bgo:headerTitle "Title" ;
    bgo:headerAmount "Amount" ;
    bgo:headerTrend "Trend" ;
    bgo:headerDescription "Description" ;
.

:overview
	# a bgo:Overview ;
	bgo:label "Geral" ;
	bgo:icon "fas fa-atom" ;
	bgo:title "Overview" ;
	bgo:hasPartitions [
		# a bgo:Partitions ;
		bgo:icon "fas fa-atom" ;
		bgo:label "Partitions";
	    bgo:hasPartition
	        :p1 ,
	        :p2
    ];
	bgo:hasTrendColorScheme :trend_color_scheme ;
    bgo:hasTotalizer :filtered_total_formatter ;
    bgo:hasTagCloud :tag_cloud ;
    bgo:hasSearchPane :search_pane ;
    bgo:hasTooltip [
    	# a bgo:Tooltip ;
	    bgo:amountFormatter :amount_formatter;
	    bgo:referenceFormatter :amount_formatter;
	    bgo:trendFormatter :trend_formatter
	] ;
.



:filtered_total_formatter
    # a bgo:Totalizer ;
	bgo:format "Totale:  € %s" ;
	bgo:filteredFormat "In evidenza: € %s"^^bgo:Template  ;
	bgo:precision 2 ;
	bgo:ratioFormatter [
		# a bgo:NumberFormatter
		bgo:format " ( %s% del tot.)"^^bgo:Template  ;
		bgo:precision 2 ;
		bgo:scaleFactor 100 ;
		bgo:maxValue 100 ;
		bgo:minValue 1 ;
		bgo:moreThanMaxFormat "" ;
		bgo:lessThanMinFormat " (< 1% del tot.)"
	]
.

##### P1
:p1
	# a bgo:Partition ;
	bgo:partitionId "p1" ;
	bgo:label "partition1" ;
	bgo:title "Partition 1 title" ;
	bgo:withSortOrder bgo:ascending_sort ; # or bgo:descending_sort (default)
	bgo:withSortCriteria bgo:natural_sort ; # or bgo:abs_sort (default)
	bgo:withGroupFunction [
		a bgo:AmountsSum;
		bgo:hasTotalizer [
			# a bgo:Totalizer
			bgo:format "€ %s" ;
			bgo:filteredFormat "€ %s"^^bgo:Template  ;
			bgo:precision 2 ;
			bgo:ratioFormatter :trend_formatter
		]
	];
    bgo:hasAccountSubSet
        :p1_1 ,
        :p1_2
    ;
    bgo:hasDefaultAccountSubSet [
    	# a bgo:DefaultAccountSet  ;
	    bgo:label "default" ;
	    bgo:title "Default subset for p1"
    ]
.


:p1_1
	#a bgo:AccountSet ;
    bgo:title "Subset 1_1 title" ;
    bgo:description "An account subset" ;
    bgo:abstract "This use **markdown**"^^bgo:MDString ;
    bgo:hasAccount
        :account_1
.

:p1_2
	# a bgo:AccountSet ;
    bgo:label "subset 1_2" ;
    bgo:title "Subset 2 title"
.


#### P2 ###########
:p2
	# a bgo:Partition;
	bgo:partitionId "2" ;
	bgo:label "partition2" ;
	bgo:title "P2 title" ;
    bgo:hasAccountSubSet
        :p2_1 ,
        :p2_2
    ;

    # Note no default partition is present : a default one should be create with title "Unassigned"
.

:p2_1
	# a bgo:AccountSet ;
    bgo:title "Subset 2_1 title" ;
    bgo:description "An account subset" ;
    bgo:abstract "This use **markdown**"^^bgo:MDString ;
    bgo:hasAccount
        :account_1
.

:p2_2
	# a bgo:AccountSet ;
    bgo:label "subset 2_2" ;
    bgo:title "Subset 2 title" ;
    bgo:hasAccount
        :account_2
.


###### Trend Color Scheme #######
:trend_color_scheme
	# a bgo:TrendColorScheme ;
    bgo:title "Variazione percentuale rispetto al valore di acquisto" ;
    bgo:noTrendColor "#cdcdcd"^^bgo:RGB ;
    bgo:rateTreshold # all are bgo:RateTreshold
		[ bgo:rate -1.00 ; 	bgo:colorId "#a50026"^^bgo:RGB ] ,
		[ bgo:rate -0.50 ;	bgo:colorId "#d73027"^^bgo:RGB ] ,
		[ bgo:rate -0.25 ;	bgo:colorId "#f46d43"^^bgo:RGB ] ,
		[ bgo:rate -0.10 ; bgo:colorId "#fdae61"^^bgo:RGB ] ,
		[ bgo:rate -0.05 ; bgo:colorId "#fee08b"^^bgo:RGB ] ,
		[ bgo:rate  0.0 ;	bgo:colorId "#ffffbf"^^bgo:RGB ] ,
		[ bgo:rate  0.05 ;	bgo:colorId "#d9ef8b"^^bgo:RGB ] ,
		[ bgo:rate  0.10 ;	bgo:colorId "#a6d96a"^^bgo:RGB ] ,
		[ bgo:rate 0.25 ;	bgo:colorId "#66bd63"^^bgo:RGB ] ,
		[ bgo:rate 0.50	;	bgo:colorId "#1a9850"^^bgo:RGB ] ,
		[ bgo:rate 10.00 ;	bgo:colorId "#006837"^^bgo:RGB ]
.


:search_pane
	# a bgo:SearchPane ;
    bgo:label "Cerca"
.


:tag_cloud
	# a bgo:TagCloud ;
	bgo:hasTag # all are bgo:tags
		[ bgo:label "rfgt2"; bgo:tagWeight 1.0 ] ,
		[ bgo:label "Tetrst2"; bgo:tagWeight 0.5 ] ,
		[ bgo:label "Tewsst3"; bgo:tagWeight 1.0 ] ,
		[ bgo:label "Tedgst4"; bgo:tagWeight 0.2 ] ,
		[ bgo:label "Tefgst5"; bgo:tagWeight 0.7 ] ,
		[ bgo:label "Teefst6"; bgo:tagWeight 0.3 ],
        [ bgo:label "Testsdf4"; bgo:tagWeight 0.2 ] ,
		[ bgo:label "Tegsgsbst5"; bgo:tagWeight 0.7 ] ,
		[ bgo:label "Testeag6"; bgo:tagWeight 0.3 ],
        [ bgo:label "Tesbgbt4"; bgo:tagWeight 0.2 ] ,
		[ bgo:label "Twrfegest5"; bgo:tagWeight 0.7 ] ,
		[ bgo:label "Tesqr3hyt6"; bgo:tagWeight 0.3 ]
.



#############################################
# Accounts
#############################################

## Account 1 with all the details
:account_1
	# a bgo:Account;
	bgo:accountId "account_1" ;
    bgo:amount 1000.00 ;
    bgo:referenceAmount 950.00 ;
    bgo:title "titolo account_1" ;
    bgo:description "descrizione account_1" ;
    bgo:abstract """
    Il rimborso dei titolo del debito statale tiene conto del:
    pagamento delle quote capitale sui titoli del debito statale
    rimborso del capitale relativo a buoni postali fruttiferi
    rimborso alla Banca d'Italia del controvalore delle lire presentate al cambio per il ritiro dalla circolazionerimborso passività
    a carico dello Stato.

Il passaggio standard del Lorem Ipsum, utilizzato sin dal sedicesimo secolo

"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

La sezione 1.10.32 del "de Finibus Bonorum et Malorum", scritto da Cicerone nel 45 AC

"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"

Traduzione del 1914 di H. Rackham

"But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"
"""^^bgo:MDString ;
  #  bgo:depiction <http://bit.ly/2MxbJWQ> ;
    bgo:versionLabel "2019" ;

	bgo:hasHistoryRec # All bgo:HistoryRec
		[ bgo:versionLabel "2018" ; bgo:amount 980.00 ],
		[ bgo:versionLabel "2017" ; bgo:amount 1100.00 ]
    ;
    bgo:hasBreakdown # all bgo:PartialAmount
    	[ bgo:title "account_1_part 1" ; bgo:amount 110.00 ] ,
    	[ bgo:title "account_1_part 2" ; bgo:amount 120.00 ] ,
    	[ bgo:title "account_1_part 3" ; bgo:amount 130.00 ]
    ;
.


##################################################
## Other accounts without detailed profile
###################################################
:account_2
	# a bgo:Account ;
	bgo:accountId "account_2" ;
    bgo:amount 100.00 ;
    bgo:referenceAmount 95.00 ;
    bgo:title "titolo account_2" ;
    #bgo:depiction <http://bit.ly/2MxbJWQ> ;
    bgo:description "descrizione account_2"
.

:account_3
	# a bgo:Account ;
	bgo:accountId "account_3" ;
    bgo:amount 100.00 ;
    bgo:referenceAmount 95.00 ;
    bgo:title "titolo account_3" ;
    bgo:depiction "#fcba03"  # as RGB solid color
.

:account_4
	# a bgo:Account ;
 	bgo:accountId "account_4" ;
    bgo:amount 100.00 ;
    bgo:referenceAmount 95.00
.


:account_5
	# a bgo:Account ;
 	bgo:accountId "account_5" ;
    bgo:amount 100.00
.`

And my Dockerfile looks like this:

`FROM linkeddatacenter/lodmap2d

COPY public/* /usr/share/nginx/html/`

**Comment by ecow** [comment]
Sorry, I can't replicate the problem.

- I copied public/data.ttl into public/mydata.ttl
- I edited public/mydata.ttl  changing "Stato" to "Geral" in the label of :Overview subject
- I rebuild the docker image with the command docker build -t myloadmap2d -f docker/Dockerfile .
- I run docker run -d -e LODMAP2D_DATA=http://localhost:8080/mydata.ttl -p 8080:80 myloadmap2d
- I point my chrome browser to http://localhost:8080/

Here the result:

![image](https://user-images.githubusercontent.com/5788689/117160318-4d2cb100-adc1-11eb-940d-181f13c5b8cc.png)

**Comment by gustavopdias** [comment]
Hi, I solved it by following the steps in your last comment. I also moved the mydata.ttl to the public directory, so that could also have been the roblem. Thank you so much!
